In [4]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
import time
import datetime

In [5]:
url = "https://www.amazon.com/Samsung-Galaxy-Tab-64-W129243165/dp/B0G2RNZXLZ/ref=sr_1_10?_encoding=UTF8&content-id=amzn1.sym.f0670b1b-e1fd-4c67-a2b1-b8a347243628&dib=eyJ2IjoiMSJ9.7yOrlIfk_tlEZy-WRmY6RPtjPTdh24RkqhlYtuciI5zlaU6a3ndlfLcuILJdtSP5h3atW4rugKXtLamahVsTsA-f26syEPdpmSmi2g5DuqwdhmZMZv-qWyFK3ZzZKYe6_DhoTGERtotSizXth3MkGUu-ovW6lVS0L9-ayRZrMGxlC35UAF__xQpOlISGB1qt13ibepCjh-JJojCd4u92R5LI866IV9sbywDGJTfsRB8.R-X2KyTSX0LIpxP_qzFG3_H_9SJxOlO08US8tjNll64&dib_tag=se&keywords=electronic+tablets&pd_rd_r=d09701b0-ea2f-4159-b467-d0a4fb81135f&pd_rd_w=X2lIy&pd_rd_wg=hl11s&qid=1774237860&sr=8-10"


headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9"
}

page = requests.get(url,headers=headers)
soup = BeautifulSoup(page.content,"html.parser")
soup = BeautifulSoup(soup.prettify(),"html.parser")

soup

<!DOCTYPE html>

<html class="a-no-js" data-19ax5a9jf="dingo" lang="en-us">
<!-- sp:feature:head-start -->
<head>
<script>
   var aPageStart = (new Date()).getTime();
  </script>
<meta charset="utf-8"/>
<!-- sp:end-feature:head-start -->
<!-- sp:feature:csm:head-open-part1 -->
<script type="text/javascript">
   var ue_t0=ue_t0||+new Date();
  </script>
<!-- sp:end-feature:csm:head-open-part1 -->
<!-- sp:feature:cs-optimization -->
<meta content="on" http-equiv="x-dns-prefetch-control"/>
<link crossorigin="" href="https://images-na.ssl-images-amazon.com" rel="preconnect"/>
<link crossorigin="" href="https://m.media-amazon.com" rel="preconnect"/>
<!-- sp:end-feature:cs-optimization -->
<!-- sp:feature:csm:head-open-part2 -->
<script type="text/javascript">
   window.ue_ihb = (window.ue_ihb || window.ueinit || 0) + 1;
if (window.ue_ihb === 1) {

var ue_csm = window,
    ue_hob = +new Date();
(function(d){var e=d.ue=d.ue||{},f=Date.now||function(){return+new Date};e.d=function(b){return f()-(b?0:d.ue_t0)};e.stub=function(b,a){if(!b[a]){var c=[];b[a]=function(){c.push([c.slice.call(arguments),e.d(),d.ue_id])};b[a].replay=function(b){for(var a;a=c.shift();)b(a[0],a[1],a[2])};b[a].isStub=1}};e.exec=function(b,a){return function(){try{return b.apply(this,arguments)}catch(c){ueLogError(c,{attribution:a||"undefined",logLevel:"WARN"})}}}})(ue_csm);


    var ue_err_chan = 'jserr-rw';
(function(d,e){function h(f,b){if(!(a.ec>a.mxe)&&f){a.ter.push(f);b=b||{};var c=f.logLevel||b.logLevel;c&&c!==k&&c!==m&&c!==n&&c!==p||a.ec++;c&&c!=k||a.ecf++;b.pageURL=""+(e.location?e.location.href:"");b.logLevel=c;b.attribution=f.attribution||b.attribution;a.erl.push({ex:f,info:b})}}function l(a,b,c,e,g){d.ueLogError({m:a,f:b,l:c,c:""+e,err:g,fromOnError:1,args:arguments},g?{attribution:g.attribution,logLevel:g.logLevel}:void 0);return!1}var k="FATAL",m="ERROR",n="WARN",p="DOWNGRADED",a={ec:0,ecf:0,
pec:0,ts:0,erl:[],ter:[],buffer:[],mxe:50,startTimer:function(){a.ts++;setInterval(function(){d.ue&&a.pec<a.ec&&d.uex("at");a.pec=a.ec},1E4)}};l.skipTrace=1;h.skipTrace=1;h.isStub=1;d.ueLogError=h;d.ue_err=a;e.onerror=l})(ue_csm,window);


var ue_id = 'PQJXDRWGMXFNYZCDZYEA',
    ue_url = '/rd/uedata',
    ue_drfp = true,
    ue_navtiming = 1,
    ue_mid = 'ATVPDKIKX0DER',
    ue_sid = '132-4064616-3697400',
    ue_sn = 'www.amazon.com',
    ue_furl = 'fls-na.amazon.com',
    ue_surl = 'https://unagi.amazon.com/1/events/com.amazon.csm.nexusclient.prod',
    ue_int = 0,
    ue_fcsn = 1,
    ue_urt = 3,
    ue_rpl_ns = 'cel-rpl',
    ue_ddq = 1,
    ue_fpf = '//fls-na.amazon.com/1/batch/1/OP/ATVPDKIKX0DER:132-4064616-3697400:PQJXDRWGMXFNYZCDZYEA$uedata=s:',
    ue_sbuimp = 1,
    ue_ibft = 0,
    ue_lpsi = 6000,
    ue_lob = '1',
    ue_act = '-1',
    ue_enbl_act = 1,
    ue_dsbl_cel = 1,

    ue_swi = 1;
var ue_viz=function(){(function(b,f,d){function g(){return(!(p in d)||0<d[p])&&(!(q in d)||0<d[q])}function h(c){if(b.ue.viz.length<w&&!r){var a=c.type;c=c.originalEvent;/^focus./.test(a)&&c&&(c.toElement||c.fromElement||c.relatedTarget)||(a=g()?f[s]||("blur"==a||"focusout"==a?t:u):t,b.ue.viz.push(a+":"+(+new Date-b.ue.t0)),a==u&&(b.ue.isl&&x("at"),r=1))}}for(var r=0,x=b.uex,a,k,l,s,v=["","webkit","o","ms","moz"],e=0,m=1,u="visible",t="hidden",p="innerWidth",q="innerHeight",w=20,n=0;n<v.length&&!e;n++)if(a=
v[n],k=(a?a+"H":"h")+"idden",e="boolean"==typeof f[k])l=a+"visibilitychange",s=(a?a+"V":"v")+"isibilityState";h({});e&&f.addEventListener(l,h,0);m=g()?1:0;d.addEventListener("resize",function(){var a=g()?1:0;m!==a&&(m=a,h({}))},{passive:!0});b.ue&&e&&(b.ue.pageViz={event:l,propHid:k})})(ue_csm,ue_csm.document,ue_csm.window)};window.ue_viz=ue_viz;

(function(d,h,P){function G(a){return a&&a.replace&&a.replace(/^\s+|\s+$/g,"")}function v(a){return"undefined"===typeof a}function K(a){return"function"===typeof a}function E(a,b){for(var c in b)b[w](c)&&(a[c]=b[c])}function L(a){try{var b=P.cookie.match(RegExp("(^| )"+a+"=([^;]+)"));if(b)return b[2].trim()}catch(c){}}function Q(l,b,c){var t=(B||{}).type;if("device"!==c||2!==t&&1!==t){if(l){d.ue_id=a.id=a.rid=l;if("device"===c||"pre-fetch"===c)a.oid=G(l);p&&(p=p.replace(/((.*?:){2})(\w+)/,function(a,
b){return b+l}));H&&(e("id",H,l),H=0)}b&&(p&&(p=p.replace(/(.*?:)(\w|-)+/,function(a,c){return c+b})),d.ue_sid=b);c&&a.tag("page-source:"+c);d.ue_fpf=p}}function R(){var a={};return function(b){b&&(a[b]=1);b=[];for(var c in a)a[w](c)&&b.push(c);return b}}function D(d,b,c,t){t=t||+new I;var f,h;if(b||v(c)){if(d)for(h in f=b?e("t",b)||e("t",b,{}):a.t,f[d]=t,c)c[w](h)&&e(h,b,c[h]);return t}}function e(d,b,c){var e=b&&b!=a.id?a.sc[b]:a;e||(e=a.sc[b]={});"id"===d&&c&&(S=1);return e[d]=c||e[d]}function T(d,
b,c,e,f){c="on"+c;var h=b[c];K(h)?d&&(a.h[d]=h):h=function(){};b[c]=function(a){f?(e(a),h(a)):(h(a),e(a))};b[c]&&(b[c].isUeh=1)}function U(l,b,c,t){function r(b,c){var d=[b],g=0,f={},t,k;u.latency={};c?(d.push("m=1"),f[c]=1):f=a.sc;for(k in f)if(f[w](k)){var m=e("wb",k),r=e("t",k)||{},C=e("t0",k)||a.t0,q,n;if(c||2==m){q=m?g++:"";d.push("sc"+q+"="+k);var s=z,p=z;2==m&&h.csa?(p=(s=h.csa("Content",{element:{type:"scope",slotId:k}}))&&K(s))&&+C&&s("mark","t0",+C):s=p=z;for(n in r)v(r[n])||null===r[n]||
(d.push(n+q+"="+(r[n]-C)),p&&s("mark",V[n]||n,+r[n]));d.push("t"+q+"="+r[l]);u.latency["t"+q]=r[l];if(e("ctb",k)||e("wb",k))t=1}}!A&&t&&d.push("ctb=1");return d.join("&")}function C(b,c,g,e,l){if(b){var f=d.ue_err;d.ue_url&&!d.ue_drfp&&!e&&!l&&b&&0<b.length&&(e=new Image,a.iel.push(e),e.src=b,a.count&&a.count("postbackImageSize",b.length));p?(l=h.encodeURIComponent)&&b&&(e=new Image,b=""+d.ue_fpf+l(b)+":"+(+new I-d.ue_t0),a.iel.push(e),e.src=b):a.log&&(a.log(b,"uedata",{n:1}),a.ielf.push(b));f&&!f.ts&&
f.startTimer();a.b&&(f=a.b,a.b="",C(f,c,g,1))}}function q(b){var c=B?B.type:z,d=2==c||a.isBFonMshop,c=c&&!d,e=a.bfini;if(!S||a.isBFCache)e&&1<e&&(b+="&bfform=1",c||(a.isBFT=e-1)),d&&(b+="&bfnt=1",a.isBFT=a.isBFT||1),a.ssw&&a.isBFT&&(a.isBFonMshop&&(a.isNRBF=0),v(a.isNRBF)&&(d=a.ssw(a.oid),d.e||v(d.val)||(a.isNRBF=1<d.val?0:1)),v(a.isNRBF)||(b+="&nrbf="+a.isNRBF)),a.isBFT&&!a.isNRBF&&(b+="&bft="+a.isBFT);return b}if(!a.paused&&(b||v(c))){for(var m in c)c[w](m)&&e(m,b,c[m]);a.isBFonMshop||D("pc",b,
c);m="ld"===l&&b&&e("wb",b);var n=e("id",b)||a.id;m||n===a.oid||(H=b,ea(n,(e("t",b)||{}).tc||+e("t0",b),+e("t0",b),e("pty",b),e("spty",b)));var n=e("id",b)||a.id,s=e("id2",b),g=a.url+"?"+l+"&v="+a.v+"&id="+n,A=e("ctb",b)||e("wb",b),u={eventName:l,version:a.v,id:n,sessionId:d.ue_sid||"",obfuscatedMarketplaceId:d.ue_mid||""},x;A&&(g+="&ctb="+A);s&&(g+="&id2="+s);1<d.ueinit&&(g+="&ic="+d.ueinit);if(!("ld"!=l&&"ul"!=l||b&&b!=n)){if("ld"==l){try{h[M]&&h[M].isUeh&&(h[M]=null)}catch(L){}if(h.chrome)for(s=
0;s<N.length;s++)W(J,N[s]);(s=P.ue_backdetect)&&s.ue_back&&s.ue_back.value++;d._uess&&(x=d._uess());a.isl=1}a._bf&&(g+="&bf="+a._bf());d.ue_navtiming&&f&&(e("ctb",n,"1"),a.isBFonMshop||D("tc",z,z,O));!F||a.isBFonMshop||X||(f&&E(a.t,{na_:f.navigationStart,ul_:f.unloadEventStart,_ul:f.unloadEventEnd,rd_:f.redirectStart,_rd:f.redirectEnd,fe_:f.fetchStart,lk_:f.domainLookupStart,_lk:f.domainLookupEnd,co_:f.connectStart,_co:f.connectEnd,sc_:f.secureConnectionStart,rq_:f.requestStart,rs_:f.responseStart,
_rs:f.responseEnd,dl_:f.domLoading,di_:f.domInteractive,de_:f.domContentLoadedEventStart,_de:f.domContentLoadedEventEnd,_dc:f.domComplete,ld_:f.loadEventStart,_ld:f.loadEventEnd,ntd:(K(F.now)&&!v(O)?new I(O+F.now())-new I:0)+a.t0}),B&&E(a.t,{ty:B.type+a.t0,rc:B.redirectCount+a.t0}),X=1);a.isBFonMshop||E(a.t,{hob:d.ue_hob,hoe:d.ue_hoe});a.ifr&&(g+="&ifr=1",u.ifr=!0)}D(l,b,c,t);var y,k;m||b&&b!==n||fa(b);(c=d.ue_mbl)&&c.cnt&&!m&&(g+=c.cnt());m?e("wb",b,2):"ld"==l&&(a.lid=G(n));for(y in a.sc)if(1==e("wb",
y))break;if(m){if(a.s)return;g=r(g,null)}else c=r(g,null),c!=g&&(c=q(c),a.b=c),x&&(g+=x),g=r(g,b||a.id);g=q(g);if(a.b||m)for(y in a.sc)2==e("wb",y)&&delete a.sc[y];y=0;a._rt&&(g+="&rt="+a._rt());x=h.csa;if(!m&&x)for(k in c=e("t",b)||{},t=x("PageTiming"),c)c[w](k)&&t("mark",V[k]||k,c[k]);m||(a.s=0,(k=d.ue_err)&&0<k.ec&&k.pec<k.ec&&(k.pec=k.ec,g+="&ec="+k.ec+"&ecf="+k.ecf),y=e("ctb",b),"ld"!==l||b||a.markers?a.markers&&a.isl&&!m&&b&&E(a.markers,e("t",b)):(a.markers={},E(a.markers,e("t",b))),e("t",b,
{}));a.tag&&a.tag().length&&(g+="&csmtags="+a.tag().join("|"),u.csmtags=a.tag(),a.tag=R());k=a.viz||[];if(c=k.length)k=k.splice(0,c),g+="&viz="+k.join("|"),u.viz=k;v(d.ue_pty)||(g+="&pty="+d.ue_pty+"&spty="+d.ue_spty+"&pti="+d.ue_pti,u.pty=d.ue_pty,u.spty=d.ue_spty,u.pti=d.ue_pti);a.tabid&&(g+="&tid="+a.tabid);a.aftb&&(g+="&aftb=1");!a._ui||b&&b!=n||(g+=a._ui());g+="&lob="+(d.ue_lob||"0");a.a=g;C(g,l,y,m,b&&"string"===typeof b&&-1!==b.indexOf("csa:"));m||(u.lob=d.ue_lob||"0",(b=x&&x("UEData"))&&b("log",
u))}}function fa(a){var b=h.ue_csm_markers||{},c;for(c in b)b[w](c)&&D(c,a,z,b[c])}function A(a,b,c){c=c||h;if(c[Y])c[Y](a,b,!1);else if(c[Z])c[Z]("on"+a,b)}function W(a,b,c){c=c||h;if(c[$])c[$](a,b,!1);else if(c[aa])c[aa]("on"+a,b)}function ba(){function a(){d.onUl()}function b(a){return function(){c[a]||(c[a]=1,U(a))}}var c={},e,f;d.onLd=b("ld");d.onLdEnd=b("ld");d.onUl=b("ul");e={stop:b("os")};h.chrome?(A(J,a),N.push(a)):e[J]=d.onUl;for(f in e)e[w](f)&&T(0,h,f,e[f]);d.ue_viz&&ue_viz();A("load",
d.onLd);D("ue")}function ea(e,b,c,f,r){var p=d.ue_mbl,q=h.csa,m=q&&q("SPA"),q=q&&q("PageTiming");p&&p.ajax&&p.ajax(b,c);m&&q&&(e={requestId:e,transitionType:"soft"},"string"===typeof f&&(e.pageType=f,d.ue_pty=f),"string"===typeof r&&(e.subPageType=r,d.ue_spty=r),m("newPage",e),q("mark","transitionStart",b));a.tag("ajax-transition")}d.ueinit=(d.ueinit||0)+1;var a=d.ue=d.ue||{};a.t0=h.aPageStart||d.ue_t0;a.id=d.ue_id;a.url=d.ue_url;a.rid=d.ue_id;a.a="";a.b="";a.h={};a.s=1;a.t={};a.sc={};a.iel=[];a.ielf=
[];a.viz=[];a.v="0.342060.0";a.paused=!1;var w="hasOwnProperty",J="beforeunload",M="on"+J,Y="addEventListener",$="removeEventListener",Z="attachEvent",aa="detachEvent",V={cf:"criticalFeature",af:"aboveTheFold",fn:"functional",fp:"firstPaint",fcp:"firstContentfulPaint",bb:"bodyBegin",be:"bodyEnd",ld:"loaded"},I=h.Date,F=h.performance||h.webkitPerformance,f=(F||{}).timing,B=(F||{}).navigation,O=(f||{}).navigationStart,p=d.ue_fpf,S=0,X=0,N=[],H=0,z;a.oid=G(a.id);a.lid=G(a.id);a._t0=a.t0;a.tag=R();a.ifr=
h.top!==h.self||h.frameElement?1:0;a.markers=null;a.attach=A;a.detach=W;if("000-0000000-8675309"===d.ue_sid){var ca=L("cdn-rid"),da=L("session-id");ca&&da&&Q(ca,da,"cdn")}d.uei=ba;d.ueh=T;d.ues=e;d.uet=D;d.uex=U;a.reset=Q;a.pause=function(d){a.paused=d};ba()})(ue_csm,ue_csm.window,ue_csm.document);


ue.stub(ue,"event");ue.stub(ue,"onSushiUnload");ue.stub(ue,"onSushiFlush");

ue.stub(ue,"log");ue.stub(ue,"onunload");ue.stub(ue,"onflush");
(function(b){var a=b.ue;a.cv={};a.cv.scopes={};a.cv.buffer=[];a.count=function(b,d,c){var e=a.cv;a.d();c&&c.scope&&(e=a.cv.scopes[c.scope]=a.cv.scopes[c.scope]||{});if(void 0===d)return e[b];e[b]=d;a.cv.buffer.push({c:b,v:d})};a.count("baselineCounter2",1);a&&a.event&&(a.event({requestId:b.ue_id||"rid",server:b.ue_sn||"sn",obfuscatedMarketplaceId:b.ue_mid||"mid"},"csm","csm.CSMBaselineEvent.4"),a.count("nexusBaselineCounter",1,{bf:1}))})(ue_csm);



var ue_hoe = +new Date();
}
window.ueinit = window.ue_ihb;
  </script>
<!-- 1rz0q88x0kqpti7o -->
<script>
   window.ue && ue.count && ue.count('CSMLibrarySize', 10510)
  </script>
<!-- sp:end-feature:csm:head-open-part2 -->
<!-- sp:feature:aui-assets -->
<link href="https://m.media-amazon.com/images/I/21skJF47J6L._RC|51Y8Xg9itbL.css_.css?AUIClients/AmazonUI" rel="stylesheet"/>
<link href="https://m.media-amazon.com/images/I/11T9EXq1JNL._RC|01cxwTawfML.css,41wxi7MSmOL.css,318xXDa9Z-L.css,21JMC7OC91L.css,01xH+fhFIJL.css,01EJgRrSvHL.css,413Vvv3GONL.css,1170nDgl0uL.css,01Rw4F+QU6L.css,11NeGmEx+fL.css,01LmAy9LJTL.css,01IdKcBuAdL.css,01iHqjS7YfL.css,01eVBHHaY+L.css,21D3IemrALL.css,11pDJV08stL.css,51yqRfvysvL.css,01HWrzt-WgL.css,01XPHJk60-L.css,11aX6hlPzjL.css,01GAxF7K5tL.css,01ZM-s8Z3xL.css,21gEzBqpmtL.css,11CFYS0t4PL.css,21TxBPhrLyL.css,21Dt9D2TuML.css,31GD5I7tbCL.css,111h7n9dRnL.css,31Qk3MvcMIL.css,11PDZ29p-PL.css,11kbPm9N5xL.css,215WpAjwzoL.css,11sUwulETuL.css,114aTS6SjML.css,01xFKTPySiL.css,21GcfcmbahL.css,21OD8FuBraL.css,11XozyxiH7L.css,21n1oEPZnHL.css,11HVvPbE6JL.css,119Cktja74L.css,11PMguLK6gL.css,01890+Vwk8L.css,11sjvwOAToL.css,01qiwJ7qDfL.css,21AS3Iv3HQL.css,016mfgi+D2L.css,01VinDhK+DL.css,31un+UKeIeL.css,21msrr4h2yL.css,013-xYw+SRL.css_.css?AUIClients/AmazonUI#us.not-trident" rel="stylesheet"/>
<link as="script" crossorigin="anonymous" href="https://m.media-amazon.com/images/I/61xJcNKKLXL.js?AUIClients/AmazonUIjQuery" rel="preload">
<link as="script" crossorigin="anonymous" href="https://m.media-amazon.com/images/I/11zuylp74DL._RC|11Y+5x+kkTL.js,51vYHGMfzIL.js,115zbyk371L.js,11GgN1+C7hL.js,01+z+uIeJ-L.js,01VRMV3FBdL.js,21NadQlXUWL.js,01vRf9id2EL.js,11a7qqY8xXL.js,11aZNVRA-EL.js,51C4kaFbiAL.js,11FhdH2HZwL.js,11wb9K3sw0L.js,11BrgrMAHUL.js,11GPhx42StL.js,210X-JWUe-L.js,01Svfxfy8OL.js,61070UYoWML.js,01ikBbTAneL.js,31xywoXPfpL.js,01qXJuwGmxL.js,01WlsjNmqIL.js,11F929pmpYL.js,31Zn4S+IOkL.js,01rpauTep4L.js,31rqCOnXDNL.js,011FfPwYqHL.js,21P5VvHf-XL.js,013ncka0wXL.js,21kN0q4IA-L.js,01VvIkYCafL.js,11vb6P5C5AL.js,01NjPq-AshL.js_.js?AUIClients/AmazonUI" rel="preload">
<link as="script" crossorigin="anonymous" href="https://m.media-amazon.com/images/I/517f0agMn-L.js?AUIClients/CardJsRuntimeBuzzCopyBuild" rel="preload"/>
<script>
     (function(b,a,c,d){if((b=b.AmazonUIPageJS||b.P)&&b.when&&b.register){c=[];for(a=a.currentScript;a;a=a.parentElement)a.id&&c.push(a.id);return b.log("A copy of P has already been loaded on this page.","FATAL",c.join(" "))}})(window,document,Date);(function(a,b,c,d){"use strict";a._pSetI=function(){return null}})(window,document,Date);(function(c,e,I,B){"use strict";c._pd=function(){var a,u;return function(C,f,h,k,b,D,v,E,F){function w(d){try{return d()}catch(J){return!1}}function l(){if(m){var d={w:c.innerWidth||b.clientWidth,h:c.innerHeight||b.clientHeight};5<Math.abs(d.w-q.w)||50<d.h-q.h?(q=d,n=4,(d=a.mobile||a.tablet?450<d.w&&d.w>d.h:1250<=d.w)?k(b,"a-ws"):b.className=v(b,"a-ws")):0<n&&(n--,x=setTimeout(l,16))}}function G(d){(m=d===B?!m:!!d)&&l()}function H(){return m}if(!u){u=!0;var r=function(){var d=["O","ms","Moz","Webkit"],
c=e.createElement("div");return{testGradients:function(){return!0},test:function(a){var b=a.charAt(0).toUpperCase()+a.substr(1);a=(d.join(b+" ")+b+" "+a).split(" ");for(b=a.length;b--;)if(""===c.style[a[b]])return!0;return!1},testTransform3d:function(){return!0}}}(),y=b.className,z=/(^| )a-mobile( |$)/.test(y),A=/(^| )a-tablet( |$)/.test(y);a={audio:function(){return!!e.createElement("audio").canPlayType},video:function(){return!!e.createElement("video").canPlayType},canvas:function(){return!!e.createElement("canvas").getContext},
svg:function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect},offline:function(){return navigator.hasOwnProperty&&navigator.hasOwnProperty("onLine")&&navigator.onLine},dragDrop:function(){return"draggable"in e.createElement("span")},geolocation:function(){return!!navigator.geolocation},history:function(){return!(!c.history||!c.history.pushState)},webworker:function(){return!!c.Worker},autofocus:function(){return"autofocus"in e.createElement("input")},
inputPlaceholder:function(){return"placeholder"in e.createElement("input")},textareaPlaceholder:function(){return"placeholder"in e.createElement("textarea")},localStorage:function(){return"localStorage"in c&&null!==c.localStorage},orientation:function(){return"orientation"in c},touch:function(){return"ontouchend"in e},gradients:function(){return r.testGradients()},hires:function(){var a=c.devicePixelRatio&&1.5<=c.devicePixelRatio||c.matchMedia&&c.matchMedia("(min-resolution:144dpi)").matches;E("hiRes"+
(z?"Mobile":A?"Tablet":"Desktop"),a?1:0);return a},transform3d:function(){return r.testTransform3d()},touchScrolling:function(){return f(/Windowshop|android|OS ([5-9]|[1-9][0-9]+)(_[0-9]{1,2})+ like Mac OS X|SOFTWARE=([5-9]|[1-9][0-9]+)(.[0-9]{1,2})+.*DEVICE=iPhone|Chrome|Silk|Firefox|Trident.+?; Touch/i)},ios:function(){return f(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)&&!f(/trident|Edge/i)},android:function(){return f(/android.([1-9]|[L-Z])/i)&&!f(/trident|Edge/i)},mobile:function(){return z},
tablet:function(){return A},rtl:function(){return"rtl"===b.dir}};for(var g in a)a.hasOwnProperty(g)&&(a[g]=w(a[g]));for(var t="textShadow textStroke boxShadow borderRadius borderImage opacity transform transition".split(" "),p=0;p<t.length;p++)a[t[p]]=w(function(){return r.test(t[p])});var m=!0,x=0,q={w:0,h:0},n=4;l();h(c,"resize",function(){clearTimeout(x);n=4;l()});b.className=v(b,"a-no-js");k(b,"a-js");!f(/OS [1-8](_[0-9]*)+ like Mac OS X/i)||c.navigator.standalone||f(/safari/i)||k(b,"a-ember");
h=[];for(g in a)a.hasOwnProperty(g)&&a[g]&&h.push("a-"+g.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()}));k(b,h.join(" "));b.setAttribute("data-aui-build-date",F);C.register("p-detect",function(){return{capabilities:a,localStorage:a.localStorage&&D,toggleResponsiveGrid:G,responsiveGridEnabled:H}});return a||{}}}}()})(window,document,Date);(function(a,p,q,k){function m(e,b,c,g){a.P.when.apply(a.P,b).register("flow:"+e,function(){var a=g.apply(this,arguments);return c||a})}function l(e){a.P.log(e,"FATAL","AmazonUIPageJS@AUIDefineJS")}function f(a,b,c){Object.defineProperty(a,b,{value:c,writable:!1})}function n(e,b,c){"string"!==typeof e&&a.P.error("Anonymous modules are not supported.");var g=c!==k?c:"function"===typeof b?b:k;g||a.P.error("A callback must be provided");var f,h=[];if(c&&Array.isArray(b)&&(h=b.reduce(function(b,d){if("module"===
d||"require"===d)a.P.error('"module" or "require" injection is not supported.');else if("exports"===d){d=f={};var c="flow:"+e+"-exports";a.P.declare(c,d);b.push(c)}else 0!==d.lastIndexOf("@amzn/",0)?l("Dependency "+d+" does not begin with '@amzn/'"):b.push("flow:"+d);return b},[]),b.length!==h.length))return;m(e,h,f,g)}"use strict";Object.prototype.hasOwnProperty.call(a,"aui")?l("AUIDefineJS is already present globally"):(f(a,"aui",{}),f(a.aui,"amd_define",n))})(window,document,Date);(function(g,h,E,F){function N(a){l&&l.tag&&l.tag(p(":","aui",a))}function q(a,b){l&&l.count&&l.count("aui:"+a,0===b?0:b||(l.count("aui:"+a)||0)+1)}function O(a){try{return a.test(navigator.userAgent)}catch(b){return!1}}function x(a,b,d){a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent&&a.attachEvent("on"+b,d)}function p(a,b,d,e){b=b&&d?b+a+d:b||d;return e?p(a,b,e):b}function y(a,b,d){try{Object.defineProperty(a,b,{value:d,writable:!1})}catch(e){a[b]=d}return d}function P(a,b){a.className=
Q(a,b)+" "+b}function Q(a,b){return(" "+a.className+" ").split(" "+b+" ").join(" ").replace(/^ | $/g,"")}function G(a){(a||[]).forEach(function(a){a in z||(z[a]=1,G(R[a]))})}function ea(a,b,d){var e=a.length,f=e,c=function(){f--||((d&&z.hasOwnProperty(d)?A:H).push(b),I||(m?m.set(B):setTimeout(B,0),I=!0))};for(c();e--;)S[a[e]]?c():(u[a[e]]=u[a[e]]||[]).push(c)}function fa(a,b,d,e,f){var c=h.createElement(a?"script":"link");x(c,"error",e);f&&x(c,"load",f);a?(c.type="text/javascript",c.async=!0,d&&/AUIClients|images[/]I/.test(b)&&
c.setAttribute("crossorigin","anonymous"),c.src=b):(c.rel="stylesheet",c.href=b);h.getElementsByTagName("head")[0].appendChild(c)}function T(a,b){return function(d,e){function f(){fa(b,d,c,function(b){J?q("resource_unload"):c?(c=!1,q("resource_retry"),f()):(q("resource_error"),a.log("Asset failed to load: "+d));b&&b.stopPropagation?b.stopPropagation():g.event&&(g.event.cancelBubble=!0)},e)}if(U[d])return!1;U[d]=!0;q("resource_count");var c=!0;return!f()}}function ha(a,b,d){for(var e={name:a,guard:function(c){return b.guardFatal(a,

In [6]:
title = soup.find(id = "productTitle").get_text()
price = soup.find(class_ = "aok-offscreen").get_text()

title = title.strip()
price = price.strip()[1:]

In [7]:
print(title)
print(price)

Samsung Galaxy Tab A 64 GB - 8.7 Tablet - A11, W129243165 (Tablet - A11)
244.60

In [ ]:


today = datetime.date.today()

In [ ]:
Commented this to not accidently delete all 

import csv

titles = ['Product','Price','Date']
data = [title, price, today]


if not os.path.exists("Amazon_Webscraper.csv"):

    with open("Amazon_Webscraper.csv","w", newline="",encoding='UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(titles)
        writer.writerow(data)
else:
    with open('Amazon_Webscraper.csv', 'a+', newline="", encoding='UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(data)

In [ ]:
with open('AmazonWebScraperDataset.csv', 'a+', newline='', encoding='UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(data)

In [ ]:
def check_price():

    from bs4 import BeautifulSoup
    import pandas as pd
    import requests
    import time
    import datetime

    url = "https://www.amazon.com/Samsung-Galaxy-Tab-64-W129243165/dp/B0G2RNZXLZ/ref=sr_1_10?_encoding=UTF8&content-id=amzn1.sym.f0670b1b-e1fd-4c67-a2b1-b8a347243628&dib=eyJ2IjoiMSJ9.7yOrlIfk_tlEZy-WRmY6RPtjPTdh24RkqhlYtuciI5zlaU6a3ndlfLcuILJdtSP5h3atW4rugKXtLamahVsTsA-f26syEPdpmSmi2g5DuqwdhmZMZv-qWyFK3ZzZKYe6_DhoTGERtotSizXth3MkGUu-ovW6lVS0L9-ayRZrMGxlC35UAF__xQpOlISGB1qt13ibepCjh-JJojCd4u92R5LI866IV9sbywDGJTfsRB8.R-X2KyTSX0LIpxP_qzFG3_H_9SJxOlO08US8tjNll64&dib_tag=se&keywords=electronic+tablets&pd_rd_r=d09701b0-ea2f-4159-b467-d0a4fb81135f&pd_rd_w=X2lIy&pd_rd_wg=hl11s&qid=1774237860&sr=8-10"


    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9"
    }

    page = requests.get(url,headers=headers)
    soup = BeautifulSoup(page.content,"html.parser")
    soup = BeautifulSoup(soup.prettify(),"html.parser")

    title = soup.find(id = "productTitle").get_text()
    price = soup.find(class_ = "aok-offscreen").get_text()

    title = title.strip()
    price = price.strip()[1:]
    today = datetime.date.today()

    import csv

    titles = ['Product','Price','Date']
    data = [title, price, today]

    with open("Amazon_Webscraper.csv","a+", newline="",encoding='UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(data)

In [11]:
import pandas as pd
df = pd.read_csv("Amazon_Webscraper.csv")
df

                                             Product  Price        Date
0  Samsung Galaxy Tab A 64 GB - 8.7 Tablet - A11,...  244.6  2026-03-23

In [ ]:
while True:
    check_price()
    time.sleep(86400)

Empty DataFrame
Columns: [Samsung Galaxy Tab A 64 GB - 8.7 Tablet - A11, W129243165 (Tablet - A11), 244.60, 2026-03-23]
Index: []